// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTLNHOM15.Migrations
{
    [DbContext(typeof(MvcGymContext))]
    [Migration("20230515160008_HoiVien")]
    partial class HoiVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BTLNHOM15.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenChucVu")
                        .HasColumnType("TEXT");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("BTLNHOM15.Models.GiaGoi", b =>
                {
                    b.Property<string>("MaGiaGoi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenGoi")
                        .HasColumnType("TEXT");

                    b.HasKey("MaGiaGoi");

                    b.ToTable("GiaGoi");
                });

            modelBuilder.Entity("BTLNHOM15.Models.GoiTap", b =>
                {
                    b.Property<string>("GoiID")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaGoiTap")
                        .HasColumnType("TEXT");

                    b.HasKey("GoiID");

                    b.HasIndex("MaGoiTap");

                    b.ToTable("GoiTap");
                });

            modelBuilder.Entity("BTLNHOM15.Models.HoiVien", b =>
                {
                    b.Property<string>("HoiVienID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailHV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoiTap")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Ngaybatdau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Ngayketthuc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SĐT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HoiVienID");

                    b.ToTable("HoiVien");
                });

            modelBuilder.Entity("BTLNHOM15.Models.NhanVien", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailNV")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SĐT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaID");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("BTLNHOM15.Models.ThietBi", b =>
                {
                    b.Property<string>("MaTB")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Giatien")
                        .HasColumnType("TEXT");

                    b.Property<int>("Soluong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenTB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("size")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaTB");

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("BTLNHOM15.Models.GoiTap", b =>
                {
                    b.HasOne("BTLNHOM15.Models.GiaGoi", "GiaGoi")
                        .WithMany()
                        .HasForeignKey("MaGoiTap");

                    b.Navigation("GiaGoi");
                });

            modelBuilder.Entity("BTLNHOM15.Models.NhanVien", b =>
                {
                    b.HasOne("BTLNHOM15.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });
#pragma warning restore 612, 618
        }
    }
}
